---
# This playbook is designed to be pulled and modified by an external automation tool (like Tines).
# We add a pause here to ensure the job is visible in the 'Running' state for the demo.

- name: Display Dynamic System Status
  hosts: localhost 
  gather_facts: yes
  connection: local

  vars:
    deployment_status: >
      "Default Status: Playbook has not yet been updated by Tines."

  tasks:
    - name: Log the current deployment status message
      ansible.builtin.debug:
        msg: "--- Current System Message: {{ deployment_status }} ---"

    - name: PAUSE: Keep job running for 10 seconds to allow manual verification in the UI
      # This task is added to make the job visible as 'Running' in the AAP Jobs list.
      ansible.builtin.pause:
        seconds: 10
      delegate_to: localhost # Ensures the pause runs on the control node

    - name: Simulate a lightweight change (Writing to a temporary log file inside the EE)
      ansible.builtin.command:
        cmd: "echo 'Deployment status was logged on {{ ansible_date_time.iso8601_micro }}' >> /tmp/ansible_demo.log"
